# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings

title: "Where Is Our Playground&#8253;"
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Seattle Parks and Recreation has a documented history of removing play areas and other features with no coherent plan for their timely replacement. Today we ask...  Where is our Playground&#8253;
keywords: [ "playground", "park", "recreation", "community", "neighborhood", "children", "Seattle Parks", "Seattle", "city", ]


baseurl: "" # the subpath of your site, e.g. /blog
url: "https://whereisourplayground.org" # the base hostname & protocol for your site, e.g. http://example.com
github-url: https://github.com/thewellington/whereisourplayground.org

google-analytics-id: "G-36P0YGGG1N"


# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# File Processing
#
include:
  - _redirects

exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  parks:
    output: true
    permalink: /parks/:path/ 